
POST http://localhost:8080/comment/public
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjUzMTY5Nzk1LCJleHAiOjE2NTM1Mjk3OTUsImlzcyI6Im1hemdpIHByb2R1Y3Rpb24iLCJyb2xlIjoiVVNFUiJ9.OsSQdl6AYO3cOzEsVhW9iQ9M4ubwdxlvVSA9Vnvc2S4

{
  "content": "Davomi qachon",
  "videoId": 12
}

###
GET http://localhost:8080/comment/public
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjUzMTY5Nzk1LCJleHAiOjE2NTM1Mjk3OTUsImlzcyI6Im1hemdpIHByb2R1Y3Rpb24iLCJyb2xlIjoiVVNFUiJ9.OsSQdl6AYO3cOzEsVhW9iQ9M4ubwdxlvVSA9Vnvc2S4


###
GET http://localhost:8080/comment/public
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjUzMjg2MDY1LCJleHAiOjE2NTM2NDYwNjUsImlzcyI6Im1hemdpIHByb2R1Y3Rpb24iLCJyb2xlIjoiVVNFUiJ9.rDrEJimQ14pkyxAdYR_7UKC-TONiWiKiGyf0ht0uIlI
