
POST http://localhost:8080/subscription/public
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjUzMTY5Nzk1LCJleHAiOjE2NTM1Mjk3OTUsImlzcyI6Im1hemdpIHByb2R1Y3Rpb24iLCJyb2xlIjoiVVNFUiJ9.OsSQdl6AYO3cOzEsVhW9iQ9M4ubwdxlvVSA9Vnvc2S4

{
  "channelId": 2,
  "typ": "All"
}

###
PUT http://localhost:8080/subscription/public/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjUzMTY5Nzk1LCJleHAiOjE2NTM1Mjk3OTUsImlzcyI6Im1hemdpIHByb2R1Y3Rpb24iLCJyb2xlIjoiVVNFUiJ9.OsSQdl6AYO3cOzEsVhW9iQ9M4ubwdxlvVSA9Vnvc2S4

{
  "channelId": 2,
  "status": "BLOCK"
}